version: '3'

services:
  web:
    build: .    
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:system@db:5432/pixhide
    ports:
      - "80:80"

  db:
      image: postgres:16
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=system
        - POSTGRES_DB=pixhide

volumes:
  postgres_data:
